import './css/style.css';

import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import Theme from './theme-provider';
import { AuthProvider } from './context';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const aspekta = localFont({
  src: [
    {
      path: '../public/fonts/Aspekta-700.woff2',
      weight: '700',
    },
  ],
  variable: '--font-aspekta',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${inter.variable} ${aspekta.variable} font-inter antialiased dark:bg-slate-900 bg-white text-black dark:text-slate-200 tracking-tight`}
      >
        <Theme>
          <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
            <AuthProvider>{children}</AuthProvider>
          </div>
        </Theme>
      </body>
    </html>
  );
}
